//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleConsoleApp.WeatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherService.IWeatherService")]
    public interface IWeatherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetWeatherForecast", ReplyAction="http://tempuri.org/IWeatherService/GetWeatherForecastResponse")]
        MgmUtils.Models.Forecast GetWeatherForecast(string placeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetWeatherForecast", ReplyAction="http://tempuri.org/IWeatherService/GetWeatherForecastResponse")]
        System.Threading.Tasks.Task<MgmUtils.Models.Forecast> GetWeatherForecastAsync(string placeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetPlaces", ReplyAction="http://tempuri.org/IWeatherService/GetPlacesResponse")]
        MgmUtils.PlacesModels.Places GetPlaces(string placeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetPlaces", ReplyAction="http://tempuri.org/IWeatherService/GetPlacesResponse")]
        System.Threading.Tasks.Task<MgmUtils.PlacesModels.Places> GetPlacesAsync(string placeName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherServiceChannel : ExampleConsoleApp.WeatherService.IWeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceClient : System.ServiceModel.ClientBase<ExampleConsoleApp.WeatherService.IWeatherService>, ExampleConsoleApp.WeatherService.IWeatherService {
        
        public WeatherServiceClient() {
        }
        
        public WeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MgmUtils.Models.Forecast GetWeatherForecast(string placeName) {
            return base.Channel.GetWeatherForecast(placeName);
        }
        
        public System.Threading.Tasks.Task<MgmUtils.Models.Forecast> GetWeatherForecastAsync(string placeName) {
            return base.Channel.GetWeatherForecastAsync(placeName);
        }
        
        public MgmUtils.PlacesModels.Places GetPlaces(string placeName) {
            return base.Channel.GetPlaces(placeName);
        }
        
        public System.Threading.Tasks.Task<MgmUtils.PlacesModels.Places> GetPlacesAsync(string placeName) {
            return base.Channel.GetPlacesAsync(placeName);
        }
    }
}
